name: CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Replace toc-versions
        uses: NumyAddon/ToCVersions@v1

      - name: Create Package
        uses: BigWigsMods/packager@v2
        with:
          args: -S
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Prepare for Discord webhook
        id: discord-webhook-prep
        run: |
          echo "ZIP_NAME=$(ls .release/*.zip)" >> $GITHUB_OUTPUT
          {
            echo 'CHANGELOG<<EOF'
            cat .release/*/CHANGELOG.md
            printf '\nEOF'
          } >> "$GITHUB_OUTPUT"

      - name: Notify Discord webhook
        uses: "tsickert/discord-webhook@v6.0.0"
        with:
          webhook-url: "${{secrets.DISCORD_WEBHOOK_URL}}"
          content: "[${{ github.repository }}](https://github.com/${{ github.repository }}) New version released: [${{ github.event.release.tag_name }}](https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }})"
          username: "NumyAddon"
          avatar-url: "https://avatars.githubusercontent.com/u/97855854?s=200&v=4"
          filename: ${{ steps.discord-webhook-prep.outputs.ZIP_NAME }}
          embed-title: "${{ github.repository }} ${{ github.event.release.tag_name }}"
          embed-url: "https://github.com/${{ github.repository }}"
          embed-description: "${{ steps.discord-webhook-prep.outputs.CHANGELOG }}"
          embed-author-name: "${{ github.event.release.author.login }}"
          embed-author-url: "${{ github.event.release.author.html_url }}"
          embed-author-icon-url: "${{ github.event.release.author.avatar_url }}"
